services:
  ingress:
    image: nginx:stable-alpine3.20
    container_name: ingress
    hostname: ingress
    ports:
      - "443:443"
    volumes:
      - ./etc/tls/private/privkey.pem:/etc/tls/private/privkey.pem
      - ./etc/tls/certs/fullchain.pem:/etc/tls/certs/fullchain.pem
      - ./etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    restart: always
    depends_on:
      - sonarqube

  sonarqube:
    image: sonarqube:community
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
    restart: always

volumes:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions: