services:
  ingress:
    image: nginx:stable-alpine3.20
    container_name: ingress
    hostname: ingress
    ports:
      - "443:443"
    volumes:
      - ./etc/tls/private/privkey.pem:/etc/tls/private/privkey.pem
      - ./etc/tls/certs/fullchain.pem:/etc/tls/certs/fullchain.pem
      - ./etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    restart: always
    depends_on:
      - sonarqube

  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    hostname: sonarqube
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://postgres:5432/sonarqube
      SONAR_JDBC_USERNAME: ${SONARQUBE_USER}
      SONAR_JDBC_PASSWORD: ${SONARQUBE_PASSWORD}
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
    restart: always

  postgres:
    image: postgres:16
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_USER: ${SONARQUBE_USER}
      POSTGRES_PASSWORD: ${SONARQUBE_PASSWORD}
      POSTGRES_DB: sonarqube
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
  postgres_data: