version: "3"

services:
  nginx:
    platform: linux/amd64
    image: nginx:latest
    restart: always
    ports:
      - "8443:8443"
      - "8444:8444"
    volumes:
      - ../ingress/settings/cert.key:/etc/ssl/private/cert.key
      - ../ingress/settings/cert.crt:/etc/ssl/certs/cert.crt
      - ../ingress/settings/default.conf:/etc/nginx/conf.d/default.conf
      - ../ingress/settings/jenkins.conf:/etc/nginx/conf.d/jenkins.conf
    depends_on:
      - gitea
      - jenkins

  gitea:
    platform: linux/amd64
    build:
      dockerfile: gitea.dockerfile
    image: ${DOCKER_REGISTRY_URL}/${DOCKER_REGISTRY_ID}/gitea:${BUILD_VERSION}
    restart: always
    volumes:
      - gitea_data:/data

  jenkins:
    platform: linux/amd64
    build:
      dockerfile: jenkins.dockerfile
    image: ${DOCKER_REGISTRY_URL}/${DOCKER_REGISTRY_ID}/jenkins:${BUILD_VERSION}
    restart: always
    volumes:
      - ./edgerc:/var/jenkins_home/.edgerc
      - ./accCredentials:/var/jenkins_home/.aws/credentials
      - jenkins_data:/var/jenkins_home
    depends_on:
      - gitea

volumes:
  gitea_data:
  jenkins_data: