version: "3"

services:
  nginx:
    image: nginx:latest
    ports:
      - "8443:8443"
      - "8444:8444"
    volumes:
      - ../ingress/settings/cert.key:/etc/ssl/private/cert.key
      - ../ingress/settings/cert.crt:/etc/ssl/certs/cert.crt
      - ../ingress/settings/default.conf:/etc/nginx/conf.d/default.conf
      - ../ingress/settings/jenkins.conf:/etc/nginx/conf.d/jenkins.conf

  gitea:
    image: gitea/gitea:1.9
    volumes:
      - gitea_data:/data

  jenkins:
    image: jenkins/jenkins:lts
    volumes:
      - $HOME/.edgerc:/var/jenkins_home/.edgerc
      - $HOME/.aws/credentials:/var/jenkins_home/.aws/credentials
      - $HOME/powershell:/var/jenkins_home/powershell
      - /usr/bin/terraform:/var/jenkins_home/terraform
      - /usr/bin/akamai:/var/jenkins_home/akamai
      - /opt/powershell:/var/jenkins_home/powershell
      - jenkins_data:/var/jenkins_home

volumes:
  gitea_data:
  jenkins_data: