services:
  ingress:
    image: nginx:latest
    container_name: ingress
    hostname: ingress
    ports:
      - "443:443"
    volumes:
      - ./etc/tls/private/privkey.pem:/etc/tls/private/privkey.pem
      - ./etc/tls/certs/fullchain.pem:/etc/tls/certs/fullchain.pem
      - ./etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    restart: always
    depends_on:
      - gitea

  gitea:
    image: gitea/gitea:1.22.2
    container_name: gitea
    hostname: gitea
    ports:
      - "2222:22"
    volumes:
      - gitea_data:/data
    restart: always

volumes:
  gitea_data: