version: "3"

services:
  nginx:
    platform: linux/amd64
    image: nginx:latest
    ports:
      - "30443:8443"
      - "30444:8444"
    volumes:
      - ../ingress/settings/cert.key:/etc/ssl/private/cert.key
      - ../ingress/settings/cert.crt:/etc/ssl/certs/cert.crt
      - ../ingress/settings/default.conf:/etc/nginx/conf.d/default.conf
      - ../ingress/settings/jenkins.conf:/etc/nginx/conf.d/jenkins.conf

  gitea:
    platform: linux/amd64
    image: gitea/gitea:1.9
    volumes:
      - gitea_data:/data

  jenkins:
    platform: linux/amd64
    build: .
    image: ${DOCKER_REGISTRY_URL}/${DOCKER_REGISTRY_ID}/jenkins:${BUILD_VERSION}
    volumes:
      - $HOME/.edgerc:/var/jenkins_home/.edgerc
      - $HOME/.aws/credentials:/var/jenkins_home/.aws/credentials
      - jenkins_data:/var/jenkins_home

volumes:
  gitea_data:
  jenkins_data: