version: "3"

services:
  nginx:
    platform: linux/amd64
    image: nginx:latest
    restart: always
    ports:
      - "8443:8443"
      - "8444:8444"
    volumes:
      - ../ingress/settings/cert.key:/etc/ssl/private/cert.key
      - ../ingress/settings/cert.crt:/etc/ssl/certs/cert.crt
      - ../ingress/settings/default.conf:/etc/nginx/conf.d/default.conf
      - ../ingress/settings/jenkins.conf:/etc/nginx/conf.d/jenkins.conf
    depends_on:
      - gitea
      - jenkins

  gitea:
    platform: linux/amd64
    image: gitea/gitea:1.9
    restart: always
    volumes:
      - $HOME/.ssh/cicd_authorized_keys:/data/git/.ssh/authorized_keys
      - gitea_data:/data

  jenkins:
    platform: linux/amd64
    build: .
    image: ${DOCKER_REGISTRY_URL}/${DOCKER_REGISTRY_ID}/jenkins:${BUILD_VERSION}
    restart: always
    volumes:
      - $HOME/.edgerc:/var/jenkins_home/.edgerc
      - $HOME/.aws/credentials:/var/jenkins_home/.aws/credentials
      - $HOME/.ssh/cicd:/var/jenkins_home/.ssh/id_rsa
      - jenkins_data:/var/jenkins_home
    depends_on:
      - gitea

volumes:
  gitea_data:
  jenkins_data: